<?php
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado1 = ($a + $b - $c) * $d / $e % $b;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado2 = ($d - $a + $b) * ($c / $e) - $b;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado3 = (($a * $b) - ($d / $e) + $c) % $b + $d;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado4 = (++$a % $b + $c * $d / $e) - $a;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado5 = (--$d * $b + $a - ($c % $e)) / $b;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado6 = (++$a + $b * $d / $e - $c % $b) + $d;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado7 = ($a + $d) * $b % $e - $c + $a;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado8 = ($d - $a + $b) * ($c % $e) / $b + $a;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado9 = ($c % $a) + ($b / $e) * $d - $b;
$a = 15;
$b = 4;
$c = 8;
$d = 20;
$e = 5;
$resultado10 = (++$c * $b - $d + ($a % $e)) / $d;

echo "Resultado1"  .  $resultado1   . "\n"; 
echo "Resultado2"  .  $resultado2   . "\n"; 
echo "Resultado3"  .  $resultado3   . "\n"; 
echo "Resultado4"  .  $resultado4   . "\n"; 
echo "Resultado5"  .  $resultado5   . "\n"; 
echo "Resultado6"  .  $resultado6   . "\n"; 
echo "Resultado7"  .  $resultado7   . "\n"; 
echo "Resultado8"  .  $resultado8   . "\n"; 
echo "Resultado9"  .  $resultado9   . "\n"; 
echo "Resultado10" . $resultado10   . "\n";